### ISSUE TITLE
Alias clas name error

### ISSUE THREAD

**Issue by qitec** [cyberhouse/t3ext-news_gallery#2]
Hey,

I installed this plugin which I downloaded from github and now I get the following error (immediately after installation):

Uncaught TYPO3 Exception
#1: PHP Warning: Class 'GeorgRinger\News\Domain\Model\News' not found in /home/www/html/typo3/typo3_src-6.2.14/typo3/sysext/core/Classes/Core/ClassAliasMap.php line 180 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/home/www/html/typo3/typo3_src-6.2.14/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 101.

**Comment by AndreasA** [comment]
Are you sure you have installed the extension "news" in version 3.2.0 or higher (from git)?

**Comment by qitec** [comment]
Hey there, I had news 3.2.0 installed and now I just upgraded to the newly realeased 3.2.1 release of news. 
I run php 5.5.21 and Typo3 6.2.14. 

![alias_class_name_error](https://cloud.githubusercontent.com/assets/13276006/8643718/d057fab8-2937-11e5-8d31-e88512ee40ba.png)

**Comment by AndreasA** [comment]
Any other news related extensions installed?
Because this extension has no reference to the old model name.

EDIT: I am assuming you are using the latest master version of t3ext-news_gallery?

**Comment by qitec** [comment]
No, I only have news and t3ext-news_gallery-master installed. The only plugin that preconfigures news is t3s_bootstrap. But I don't expect any side-effects as this plugin only overwrites some templates.

**Comment by AndreasA** [comment]
Can you try to temporarily disable exceptions for warnings, install the extension, clear cache, reenable them?
In any case there has to be a call to the class alias name because otherwise that method shouldn't be called.

Though in any case I think the issue is most likely somewhere with news.
Can only say that my tests on Friday worked. 
Maybe I can retry later today - especially with old class name combinations.

**Comment by qitec** [comment]
Typo3 now shows: 
TYPO3 Fatal Error: Extension key "news_gallery" is NOT loaded! 

This is what I get after i switch from development to production in install tool. I checked again but I  don't have any static template called news_gallery that I may be able to add in my root template.

I cleared all the caches in Typo3 plus deleted typo3/typo3temp/Cache directory.

Any suggestions?

**Comment by AndreasA** [comment]
That sounds like the extension itself is not installed but referenced somewhere.
Ah, that might be the issue. Did you use git clone or something to get the extension?
If so is it in a folder called t3ext-news_gallery?
The folder actually needs to be news_gallery. t3ext in git repo is only as information that it is a typo3 ext.

**Comment by qitec** [comment]
That's it!
I downloaded it from https://github.com/cyberhouse/t3ext-news_gallery using 'Download-Zip' Button and copied the whole directory onto my extension directory. So the directory name was 't3ext-news_gallery-master' instead of just  'news_gallery'. 

Now it works:)

Thank's a lot!

**Comment by AndreasA** [comment]
Great. Maybe I should add this to the readme.
